services:
  minio:
    image: 'ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z'
    command: 'server /data --console-address ":9001"'
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_BROWSER_REDIRECT_URL=$MINIO_BROWSER_REDIRECT_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
    volumes:
      - 'minio-data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10

  mc-web-ui:
    image: ghcr.io/khashashin/mc-web-ui:latest
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    depends_on:
      - minio
    ports:
      - "3000:3000"

volumes:
  minio-data:
